name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api-image
    - name: Create the Docker container
      run: docker create --name api-container -p 5000:5000 api-image
    - name: Run the container
      run: docker start api-container

